print("Hello World!")
print("What is your name?")
name = input("My name is ")
print("Nice to meet you, "+ name)
print("The length of your name is: ")
print(len(name))
print("How old are you?")
age = int(input("My age is "))
print("You will be " + str(age+1) +" next year")